services:

  app:
    image: binguslover/valuesimplifier:app
    build:
      context: .
      dockerfile: Dockerfile.app
      target: prod
    ports:
      - "3000:3000"
    environment:
      MINIO_PORT: "9000"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SQL_HOST: postgres
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_HOST: minio
      MINIO_PUBLIC_URL: http://minio.railway.internal:9000
      REDIS_HOST: redis
      PORT: 3000
      MINIO_BUCKET1: processed 
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "300"
    depends_on:
      - postgres
      - redis
      - minio 
    volumes:
      - .:/app #remove for nondev
      - /app/node_modules #remove for nondev
      - ./temp:/app/temp
    command: npx nodemon back/server.js #remove for nondev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/checkHealth', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s

  worker:
    image: binguslover/valuesimplifier:worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      PYTHONUNBUFFERED: "1"
      REDIS_HOST: redis
      MINIO_HOST: minio
      MINIO_PORT: "9000"
      MINIO_PUBLIC_URL: http://minio.railway.internal:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET1: ${MINIO_BUCKET1:-processed}
    depends_on:
      - redis
      - minio
    volumes:
      - .:/app
      - ./temp:/app/temp
      - ./temp2:/app/temp2
    #command: python worker.py #remove the one below for nondev and reenable this
    command: python -m watchfiles "python back/worker/worker.py" /app/back/worker 
    restart: unless-stopped

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:8.4
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_PORT: "9000"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
      - ./temp2:/app/temp
    restart: unless-stopped
volumes:
  pgdata:
  redisdata:
  minio_data:
  temp:
  temp2: